# Generated by Django 5.2.6 on 2025-09-19 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0002_alter_testing_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testing',
        ),
    ]
