# Generated by Django 5.2.6 on 2025-09-20 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('landingpage', '0003_delete_testing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(upload_to='media/feature/')),
            ],
        ),
        migrations.CreateModel(
            name='NewRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('product_category', models.CharField(max_length=100)),
                ('description', models.CharField()),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='media/new_release/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('product_category', models.CharField(max_length=100)),
                ('description', models.CharField()),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='media/products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
