# Generated by Django 5.2.6 on 2025-09-20 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0005_alter_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(upload_to='category/'),
        ),
        migrations.AlterField(
            model_name='newrelease',
            name='image',
            field=models.ImageField(upload_to='new_release/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/'),
        ),
    ]
